# Generated by Django 6.1.1 on 2026-10-04 20:27

import django.db.models.deletion
import uuid
import vehiculos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patente', models.CharField(max_length=7, unique=True, validators=[vehiculos.models.validar_patente])),
                ('categoria', models.CharField(blank=True, choices=[('AUTO', 'Auto'), ('MOTO', 'Moto'), ('CAMIONETA', 'Camioneta')], max_length=10, null=True)),
                ('estado_validacion', models.CharField(choices=[('PENDIENTE', 'Pendiente de validación'), ('VALIDADO', 'Validado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=10)),
                ('validado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='ConsultaPatente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resultado', models.CharField(choices=[('OK', 'Encontrada'), ('NO_ENCONTRADA', 'No encontrada'), ('ERROR', 'Servicio no disponible')], max_length=15)),
                ('respuesta', models.JSONField(blank=True, default=dict)),
                ('consultado_en', models.DateTimeField(auto_now_add=True)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='vehiculos.vehiculo')),
            ],
            options={
                'ordering': ['-consultado_en'],
            },
        ),
        migrations.AddConstraint(
            model_name='vehiculo',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('estado_validacion', 'VALIDADO'), _negated=True), ('categoria__isnull', False), _connector='OR'), name='vehiculo_validado_con_categoria'),
        ),
    ]
