# Generated by Django 6.1.1 on 2026-10-04 20:27

import django.core.validators
import django.db.models.deletion
import garajes.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Garaje',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('cuit', models.CharField(max_length=13, validators=[garajes.models.validar_cuit])),
                ('direccion', models.CharField(max_length=255)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('-90')), django.core.validators.MaxValueValidator(Decimal('90'))])),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('-180')), django.core.validators.MaxValueValidator(Decimal('180'))])),
                ('capacidad', models.PositiveIntegerField()),
                ('cupo_abonos', models.PositiveIntegerField(default=0)),
                ('tolerancia_min', models.PositiveIntegerField(default=10)),
                ('salida_estimada_default_min', models.PositiveIntegerField(default=120)),
                ('recargo_overstay', models.DecimalField(decimal_places=2, default=Decimal('0.50'), help_text='0.50 = 50 % de recargo sobre la fracción de overstay.', max_digits=4)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(limit_choices_to={'rol': 'ADMIN_GARAJE'}, on_delete=django.db.models.deletion.PROTECT, related_name='garajes_administrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('categoria', models.CharField(choices=[('AUTO', 'Auto'), ('MOTO', 'Moto'), ('CAMIONETA', 'Camioneta')], max_length=10)),
                ('modalidad', models.CharField(choices=[('HORA', 'Por hora'), ('SEMANAL', 'Abono semanal'), ('MENSUAL', 'Abono mensual'), ('ANUAL', 'Abono anual')], default='HORA', max_length=10)),
                ('precio_fraccion', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fraccion_min', models.PositiveIntegerField(blank=True, null=True)),
                ('minimo_fracciones', models.PositiveIntegerField(blank=True, null=True)),
                ('precio_periodo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('garaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifas', to='garajes.garaje')),
            ],
            options={
                'ordering': ['garaje', 'categoria', 'modalidad'],
            },
        ),
        migrations.AddIndex(
            model_name='garaje',
            index=models.Index(fields=['lat', 'lng'], name='garaje_ubicacion_idx'),
        ),
        migrations.AddConstraint(
            model_name='garaje',
            constraint=models.CheckConstraint(condition=models.Q(('capacidad__gt', 0)), name='capacidad_positiva'),
        ),
        migrations.AddConstraint(
            model_name='garaje',
            constraint=models.CheckConstraint(condition=models.Q(('cupo_abonos__lte', models.F('capacidad'))), name='cupo_abonos_valido'),
        ),
        migrations.AddConstraint(
            model_name='garaje',
            constraint=models.CheckConstraint(condition=models.Q(('recargo_overstay__gte', 0)), name='recargo_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='tarifa',
            constraint=models.UniqueConstraint(fields=('garaje', 'categoria', 'modalidad'), name='tarifa_unica_por_categoria_modalidad'),
        ),
        migrations.AddConstraint(
            model_name='tarifa',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('fraccion_min__gt', 0), ('minimo_fracciones__gte', 1), ('modalidad', 'HORA'), ('precio_fraccion__gt', 0), ('precio_periodo__isnull', True)), models.Q(models.Q(('modalidad', 'HORA'), _negated=True), ('fraccion_min__isnull', True), ('minimo_fracciones__isnull', True), ('precio_fraccion__isnull', True), ('precio_periodo__gt', 0)), _connector='OR'), name='tarifa_campos_segun_modalidad'),
        ),
    ]
